config/routes.rb
Rails.application.routes.draw do

  root "institutions#index"
  resources :institutions

end

app/models/authority.rb
class Authority < ActiveRecord::Base
end

app/models/institution.rb
class Institution < ActiveRecord::Base
  def return_total(authority)
    @answer = 0
    Institution.where("authority = ?", authority).each do |institution|
      @answer += institution.number_entered
    end
    return @answer
  end

  def distinction_rate(id)
    @inst = Institution.find(id)
    @total = @inst.number_entered
    @base = @inst.distinction_1
    @base += @inst.distinction_2
    @base += @inst.distinction_3
    answer = @base.to_f / @total.to_f
    return answer

  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/institutions_controller.rb
class InstitutionsController < ApplicationController

  def index
    @institutions = Institution.all
    @my_authorities = []
    @institutions.group(:authority).each do |autho|
      @my_authorities << autho.authority
    end
   @my_results_hash = Hash.new
   @my_authorities.each do |authority|
      @my_results_hash[authority] = Institution.first.return_total(authority).to_i
    end
    @my_results_hash = @my_results_hash.sort_by{|k,v| v}.reverse.to_h
  end

  def show
    @institutions = Institution.where("authority = ?", params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  require 'csv'
  def convert_to_active_record
    read_csv
    build_files
  end

  def read_csv
     @my_data = Hash.new
     CSV.foreach("mydata.csv", :headers => true, :header_converters => :symbol, :converters => :all) do |row|
       @my_data[row.fields[0]] = Hash[row.headers[1..-1].zip(row.fields[1..-1])]
     end
    puts "CSV successfully read!"
  end

  def to_do
    #do a dir foreach when it's working
  end

  def build_files

    @my_data.keys.each do |this_key|
      Institution.create(
        :authority => this_key,
        :URN => @my_data[this_key][:urn],
        :name => @my_data[this_key][:school_or_college_name],
        :school_type => @my_data[this_key][:institution_type],
        :qualification => @my_data[this_key][:qualification],
        :number_entered => @my_data[this_key][:number_entered],
        :distinction_1 => @my_data[this_key][:distinction_1],
        :distinction_2 => @my_data[this_key][:distinction_2],
        :distinction_3 => @my_data[this_key][:distinction_3],
        :merit_1 => @my_data[this_key][:merit_1],
        :merit_2 => @my_data[this_key][:merit_2],
        :merit_3 => @my_data[this_key][:merit_3],
        :pass_1 => @my_data[this_key][:pass_1],
        :pass_2 => @my_data[this_key][:pass_2],
        :pass_3 => @my_data[this_key][:pass_3],
        :no_result => @my_data[this_key][:no_results],
        :subject => @my_data[this_key][:subject]
        )
      puts "Built new Premium with #{this_key}"
    end
  end
end

app/helpers/institutions_helper.rb
module InstitutionsHelper
end

app/views/institutions/index.html.erb
<div class="row">
  <div class="col-md-12 title-block">
    <h2>Top Entries By Authority</h2>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <table>
      <thead>
        <th>Authority</th>
        <th>Total Number Entered</th>
        <th>See all schools in authority</th>
      </thead>
      <% @my_results_hash.each do |key, value| %>
        <tr>
          <td><strong><%= key %></strong> </td>
          <td><%= value %> </td>
          <td><%= link_to "CLICK HERE", institution_path(key) %></td>
        </tr>
      <% end %>
    </table>

  </div>
</div>

app/views/institutions/show.html.erb
<div class="row">
  <div class="col-md-12 title-block">
    <h2><%= @institutions.first.authority %></h2>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <%= link_to "Home Page", root_path %>
    <table>
      <thead>
        <th>Name</th>
        <th>School Type</th>
        <th>Qualification</th>
        <th>Subject</th>
        <th>Number Entered</th>
        <th class="highlight">Distinction Rate</th>
      </thead>
      <% @institutions.each do |institution| %>
        <tr>
          <td><%= institution.name %></td>
          <td><%= institution.school_type %></td>
          <td><%= institution.qualification %></td>
          <td><%= institution.subject %></td>
          <td><%= institution.number_entered %></td>
          <td class="highlight"><strong><%= number_to_percentage((institution.distinction_rate(institution.id)*100)) %></strong></td>
        </tr>
      <% end %>
    </table>

  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Practicetwo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <%= yield %>
  </div>
</body>
</html>